### ISSUE TITLE
Cannot find module './CSSToMatrix'

### ISSUE THREAD

**Issue by prabhatojha** [daybrush/css-to-mat#1]
## Environments
* Framework name: Angular
* Framework version: 9
* Moveable Component version: 0.15.4
* Testable Address(optional):

## Description

When I build the project in Mac or Windows it works, but fails in Linux machine with following error.

> ERROR in node_modules/css-to-mat/declaration/index.esm.d.ts:1:115 - error TS2307: Cannot find module './CSSToMatrix'.
217 |  
218 | 1 export { parse, parseMat, toMat, getDistElementMatrix, caculateMatrixDist, getElementMatrix, createMatrix, } from "./CSSToMatrix";

After executing "npm install" I have observe that, the export statement is still old one with upper case in the file "index.esm.d.ts" and linux doesn't support case insensitive file names.

```
export { parse, parseMat, toMat, getDistElementMatrix, caculateMatrixDist, getElementMatrix, createMatrix, } 
from "./CSSToMatrix";

```

Please have a look, if you could help me resolve this issue.

**Comment by daybrush** [comment]
@prabhatojha 

css-to-mat 0.1.7 is released.

It seems like an uppercase/lowercase issue in the file. Republished. Uninstall and try to reinstall again.

**Comment by prabhatojha** [comment]
Thanks daybrush for a quick response. This works 👍
